### ISSUE TITLE
Error at startup making impossible to run Luna Studio

### ISSUE THREAD

**Issue by radeusgd** [luna/luna-studio#1355]
### General Summary

Upon opening the editor and error with loading `luna-studio` package shows up and the editor is completely empty, nothing can be done.

### Steps to Reproduce

Download 1.8.0.7 on Windows 10 x64 and run Luna Studio from the installer.

### Expected Result

Editor working as usual - seeing the startup page.

### Actual Result

Got following error:

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [luna-studio](...) package 1.0.0

### Stack Trace

Failed to activate the luna-studio package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:/Program Files/LunaStudio/1.8.0.7/third-party/Atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:/Program Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/src/module-cache.js:354:58)
    at Module.require (C:/Program%20Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/static/index.js:40:43)
    at require (C:/Program Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/luna-studio/lib/main.coffee:2:12)
    at /packages/luna-studio/lib/main.coffee:2:1)
    at Module.get_Module._compile (C:/Program Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (C:/Program Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (C:/Program%20Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (C:/Program Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (C:/Program Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/src/package.js:887:35)
    at Package.module.exports.Package.activateNow (C:/Program Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/src/package.js:242:22)
    at C:/Program Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (C:/Program Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/src/package.js:99:21)
    at C:/Program Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (C:/Program Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (C:/Program Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/src/package-manager.js:645:40)
    at C:/Program Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (C:/Program Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (C:/Program Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (C:/Program Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/src/package-manager.js:603:52)
    at C:/Program Files/LunaStudio/1.8.0.7/third-party/Atom/resources/app/src/atom-environment.js:846:34
```

### Commands

```
  3x -0:27.5.0 dev-live-reload:reload-all (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
column-select 0.2.0 
cursor-history 0.11.1 
file-icons 2.1.11 
hasklig 0.4.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
luna-dark-ui 0.1.1 
luna-dpi 0.1.2 
luna-studio 1.0.0 
luna-syntax 0.1.0 
minimap 4.29.6 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
multi-cursor 2.1.5 
sort-lines 0.14.0 
```

### Luna Version

1.8.0.7

**Comment by radeusgd** [comment]
1.8.0.3 works ok, so the regression must have happened somewhere in between.

**Comment by mwu-tow** [comment]
Yes, must be side-effect of the current work on packaging infrastructure. I will investigate.
