### ISSUE TITLE
Dev packages since 1.8.0.28 are broken

### ISSUE THREAD

**Issue by mwu-tow** [luna/luna-studio#1365]
### General Summary
The error in `file-icons` package is reported.

### Steps to Reproduce
Start Luna Studio, open sample project.

### Expected Result
Error is reported:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [file-icons](https://github.com/file-icons/atom) package 2.1.11

### Stack Trace

Failed to activate the file-icons package

```
At Unexpected token ...

SyntaxError: Unexpected token ...
    at Module.get_Module._compile (C:/Program Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (C:/Program Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (C:/Program%20Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/static/index.js:47:45)
    at require (C:/Program Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/file-icons/lib/service/strategies/linguist-strategy.js:4:20)
    at Module.get_Module._compile (C:/Program Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (C:/Program Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (C:/Program%20Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/static/index.js:47:45)
    at require (C:/Program Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/src/native-compile-cache.js:66:33)
    at StrategyManager.init (/packages/file-icons/lib/service/strategy-manager.js:18:4)
    at IconService.init (/packages/file-icons/lib/service/icon-service.js:23:19)
    at Object.activate (/packages/file-icons/lib/main.js:20:15)
    at Package.module.exports.Package.activateNow (C:/Program Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/src/package.js:253:25)
    at C:/Program Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (C:/Program Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/src/package.js:99:21)
    at C:/Program Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (C:/Program Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (C:/Program Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/src/package-manager.js:645:40)
    at C:/Program Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (C:/Program Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (C:/Program Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (C:/Program Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/src/package-manager.js:603:52)
    at C:/Program Files/LunaStudio/1.8.0.29/third-party/Atom/resources/app/src/atom-environment.js:846:34
```

### Commands

```
     -9:02.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-luna-syntax.theme-luna-dark-ui)
     -9:02.1.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-luna-syntax.theme-luna-dark-ui)
```

### Non-Core Packages

```
column-select 0.2.0 
cursor-history 0.11.1 
file-icons 2.1.11 
hasklig 0.4.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
luna-dark-ui 0.1.1 
luna-dpi 0.1.2 
luna-studio 1.0.0 
luna-syntax 0.1.0 
minimap 4.29.6 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
multi-cursor 2.1.5 
sort-lines 0.14.0 
```

### Luna Version
1.8.0.28

**Comment by mwu-tow** [comment]
The issue is caused because `file-icons` has dependencies without bound versions and `micromatch` packages was implicitly bumped from `4.0.1` to `3.1.10`.

`file-icons` fixed the micromatch version at ^3.1.10 beginning with https://github.com/file-icons/atom/commit/28b6f2846c0b9e4a5b5ca73840a0ee8f2d64d008

So likely we need to just bump file-icons version, along with necessary adjustments (if any).
