### ISSUE TITLE
Error on Load - May be related to tutorials not loading?

### ISSUE THREAD

**Issue by jpoles1** [luna/luna-studio#702]
Uncaught TypeError: parsed.forEach is not a function
C:\Users\jpole\.luna\config\luna-studio\1.0\atom\packages\luna-studio\lib\projects.coffee:160
Hide Stack Trace
TypeError: parsed.forEach is not a function
    at Request._callback (file:///C:/Users/jpole/.luna/config/luna-studio/1.0/atom/packages/luna-studio/lib/projects.coffee:160:32)
    at Request.self.callback (C:\Users\jpole\.luna\config\luna-studio\1.0\atom\packages\settings-view\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\jpole\.luna\config\luna-studio\1.0\atom\packages\settings-view\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\jpole\.luna\config\luna-studio\1.0\atom\packages\settings-view\node_modules\request\request.js:1085:12)
    at IncomingMessage.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

![image](https://user-images.githubusercontent.com/366282/35046701-c5bc635c-fb65-11e7-9a49-26e5529b8423.png)
 Tutorials will never load.

**Comment by pmlodawski** [comment]
Hi @jpoles1, thank you for your bug report! 

Yes, that's exactly the same problem as #684. I'm closing this as duplicate. 

In the meantime while we are preparing an update, you can download tutorials manually from https://github.com/luna-packages and open them in `luna-studio` with `Cmd-O` / `Ctrl-Shift-O`
