### ISSUE TITLE
#732 - cannot read property enumerator - occurs for me too

### ISSUE THREAD

**Issue by rbtcollins** [luna/luna-studio#746]
Leading up to this I:
1. installed LunaStudio
2. ran the tutorial and got stuck when I could not click on the radius port
3. double clicked on the deprecation warning showing in the UI in the bottom right
4. updated all the plugins
5. changed the theme to the atom light ones so that I could actually read what was going on easily
6. retried the tutorial and found that the themes combined badly and it was worse than before - backwards drop shadows in effect
7. reinstated the luna theme
8. there was an error about compiling the theme
9. restarted and now it comes up with an empty window, none of the luna components, and this in the console log:

```index.js:87 TypeError: Cannot read property 'numerator' of undefined
    at Node.Dimension.operate (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\tree\dimension.js:83:58)
    at Node.Operation.eval (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\tree\operation.js:31:18)
    at C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\tree\call.js:31:54
    at Array.map (native)
    at Node.Call.eval (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\tree\call.js:31:26)
    at Node.Expression.eval (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\tree\expression.js:31:37)
    at Node.Value.eval (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\tree\value.js:18:30)
    at Node.Rule.eval (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\tree\rule.js:56:33)
    at Node.Ruleset.eval (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\tree\ruleset.js:149:50)
    at module.exports (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\transform-tree.js:67:22)
    at ParseTree.toCSS (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\parse-tree.js:14:25)
    at C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\render.js:31:40
    at C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\parse.js:63:17
    at Object.finish [as _finish] (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\parser\parser.js:183:28)
    at Object._onSequencerEmpty (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\visitors\import-visitor.js:35:14)
    at ImportSequencer.tryRun (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\visitors\import-sequencer.js:50:14)
    at Object.run (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\visitors\import-visitor.js:29:25)
    at Object.parse (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\parser\parser.js:189:22)
    at Object.parse (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\parse.js:61:18)
    at Object.render (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less\lib\less\render.js:25:18)
    at C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less-cache\lib\less-cache.js:318:27
    at LessCache.module.exports.LessCache.observeImportedFilePaths (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less-cache\lib\less-cache.js:200:15)
    at LessCache.module.exports.LessCache.parseLess (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less-cache\lib\less-cache.js:317:28)
    at LessCache.module.exports.LessCache.cssForFile (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less-cache\lib\less-cache.js:357:25)
    at LessCache.module.exports.LessCache.readFileSync (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\node_modules\less-cache\lib\less-cache.js:340:27)
    at LessCompileCache.module.exports.LessCompileCache.read (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\src\less-compile-cache.js:39:31)
    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\src\theme-manager.js:304:39)
    at ThemeManager.module.exports.ThemeManager.loadStylesheet (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\src\theme-manager.js:271:27)
    at ThemeManager.module.exports.ThemeManager.requireStylesheet (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\src\theme-manager.js:191:30)
    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (C:\Program Files\LunaStudio\1.0\third-party\Atom\resources\app\src\theme-manager.js:252:25)handleSetupError @ index.js:87
Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError```

**Comment by wdanilo** [comment]
Hi @rbtcollins, there is a lot happening here. Does removing %HOME%.luna folder and running Luna Studio again brings Luna to working state again ?

**Comment by rbtcollins** [comment]
I would try but I already deleted both the luna directory out of program files and the .luna from %HOME%, and now the luna installer claims that luna is already installed. (I manually deleted the program files subdir because I couldn't find an uninstaller)

**Comment by wdanilo** [comment]
Yep, we do not provide nice uninstaller gui yet, however it should be simple. Linu uninstallation is just removing `~/.luna`, MacOs removing `~/.luna` and `~/Applications/LunaStudio` and Windows should behave the same way. @sylwiabr do you know why Luna Installer still thinks Luna Studio is already installed here?

**Comment by rbtcollins** [comment]
I think it might be because the services are still registered

**Comment by rbtcollins** [comment]
nope, have removed those and still an issue

**Comment by rbtcollins** [comment]
c:\program files\LunaStudio still existed even though I'd deleted it - probably a leftover from the service or some such; deleted it again and now the installer is downloading. Will try to reproduce and then test the user config removal after this.
