### ISSUE TITLE
Fatal Error: Connection Closed

### ISSUE THREAD

**Issue by dburton1221** [luna/luna-studio#796]
Connection closed.

======= logs: =======

=== s-luna-empire.wrapper.log ===
2018-02-02 15:15:33,063 INFO  - Starting ServiceWrapper in the CLI mode
2018-02-02 15:15:33,837 FATAL - Unhandled exception
System.Exception: Installation failure: Service with id 's-luna-empire' already exists
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
2018-02-02 15:15:36,720 INFO  - Starting ServiceWrapper in the CLI mode
2018-02-02 15:15:37,449 INFO  - Completed. Exit code is 0

**Comment by kustosz** [comment]
Closing as duplicate #793
