### ISSUE TITLE
luna-studio Atom package fails to activate, "cannot find module first-mate".

### ISSUE THREAD

**Issue by binary132** [luna/luna-studio#814]
1. Build Luna Studio from source using `luna-manager develop luna-studio --path ...`
2. `./dist/bin/main/luna-studio --develop`

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.13.3
**Thrown From**: [luna-studio](...) package 1.0.0

### Stack Trace

Failed to activate the luna-studio package

```
At Cannot find module 'first-mate'

Error: Cannot find module 'first-mate'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/luna-studio/atom/lib/luna-grammar.coffee:1:13)
    at Object.<anonymous> (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/luna-studio/atom/lib/luna-grammar.coffee:1:1)
    at Module.get_Module._compile (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/luna-studio/atom/lib/main.coffee:14:23)
    at Object.<anonymous> (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/luna-studio/atom/lib/main.coffee:2:1)
    at Module.get_Module._compile (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/package.js:887:35)
    at Package.module.exports.Package.activateNow (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/package.js:242:22)
    at /Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Users/bodie/meta/dev/workshop/workspace/luna-develop/apps/luna-studio/dist/third-party/Atom.app/Contents/Resources/app/src/atom-environment.js:846:34
```

### Commands

```
  3x -0:38.1.0 dev-live-reload:reload-all (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
busy-signal 1.4.3 
color-picker 2.2.5 
column-select 0.2.0 
cursor-history 0.11.1 
custom-window-title 1.0.4 
file-icons 2.1.11 
git-blame 1.2.2 
git-history 3.3.0 
git-log 0.4.1 
git-plus 7.9.3 
hasklig 0.4.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-gitignore 0.3.0 
language-haskell 1.13.2 
luna-dark-ui 0.1.1 
luna-dpi 0.1.2 
luna-studio 1.0.0 
luna-syntax 0.1.0 
minimap 4.29.6 
minimap-codeglance 0.4.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
multi-cursor 2.1.5 
sort-lines 0.14.0 
split-diff 1.5.0 
web-view 3.0.0 
```

**Comment by binary132** [comment]
I think this may have been caused by a failed `gyp install` during build.  I'll reopen if it's not the case.
