### ISSUE TITLE
PermissionError: [Errno 13] Permission denied while installing Luna Studio in Windows 10

### ISSUE THREAD

**Issue by niutech** [luna/luna-studio#818]
I cannot install Luna Studio 1.1 beta in Windows 10 using `lunaInstaller.exe` run as Administrator:

```
[19272] Failed to execute script tar2
Traceback (most recent call last):
  File "tar2.py", line 51, in <module>
  File "tar2.py", line 48, in run
  File "tar2.py", line 41, in unpack_tar
  File "tarfile.py", line 2038, in extract
  File "tarfile.py", line 2108, in _extract_member
  File "tarfile.py", line 2148, in makefile
PermissionError: [Errno 13] Permission denied: 'C:\\tmp\\luna\\luna-studio-windows-1\\luna-studio\\user-config\\atom\\packages\\luna-dark-ui\\.git\\objects\\pack\\pack-41350ad5cdfa9a7c9eaa1bb714594cce132e042d.idx'
error running: C:\tmp\luna\tar2.exe untar luna-studio-windows-1.1.tar.gz C:\tmp\luna\luna-studio-windows-1
exit status: -1
stderr: [19272] Failed to execute script tar2
Traceback (most recent call last):
  File "tar2.py", line 51, in <module>
  File "tar2.py", line 48, in run
  File "tar2.py", line 41, in unpack_tar
  File "tarfile.py", line 2038, in extract
  File "tarfile.py", line 2108, in _extract_member
  File "tarfile.py", line 2148, in makefile
PermissionError: [Errno 13] Permission denied: 'C:\\tmp\\luna\\luna-studio-windows-1\\luna-studio\\user-config\\atom\\packages\\luna-dark-ui\\.git\\objects\\pack\\pack-41350ad5cdfa9a7c9eaa1bb714594cce132e042d.idx'
```

**Comment by wdanilo** [comment]
Issue moved to [luna/luna-manager #159](https://github.com/luna/luna-manager/issues/159) via [**ZenHub**](https://www.zenhub.com/)
