### ISSUE TITLE
Cleanup the GUI

### ISSUE THREAD

**Issue by kustosz** [luna/luna-studio#914]
– Purge old GUI
– autorun new GUI

**Comment by sylwiabr** [comment]
Hello, @piotrMocz here.

That's the error when running the package on Fedora 28. Seems we haven't removed all of the libraries...
```
Uncaught TypeError: Cannot read property 'getExtension' of null
/home/sylwia/.luna/config/luna-studio/1.4.0.19/atom/packages/luna-studio/node_modules/luna-basegl-ui/dist/js/bundle.js:20768
Hide Stack Trace
TypeError: Cannot read property 'getExtension' of null
    at Object.get (/home/sylwia/.luna/config/luna-studio/1.4.0.19/atom/packages/luna-studio/node_modules/luna-basegl-ui/dist/js/bundle.js:20768:20)
    at initGLContext (/home/sylwia/.luna/config/luna-studio/1.4.0.19/atom/packages/luna-studio/node_modules/luna-basegl-ui/dist/js/bundle.js:27893:14)
    at new WebGLRenderer (/home/sylwia/.luna/config/luna-studio/1.4.0.19/atom/packages/luna-studio/node_modules/luna-basegl-ui/dist/js/bundle.js:27940:2)
    at Scene.initWebGLRenderer (/home/sylwia/.luna/config/luna-studio/1.4.0.19/atom/packages/luna-studio/node_modules/luna-basegl-ui/dist/js/bundle.js:97518:16)
    at Scene.init (/home/sylwia/.luna/config/luna-studio/1.4.0.19/atom/packages/luna-studio/node_modules/luna-basegl-ui/dist/js/bundle.js:97491:39)
    at Scene.Composable (/home/sylwia/.luna/config/luna-studio/1.4.0.19/atom/packages/luna-studio/node_modules/luna-basegl-ui/dist/js/bundle.js:618:10)
    at Scene (/home/sylwia/.luna/config/luna-studio/1.4.0.19/atom/packages/luna-studio/node_modules/luna-basegl-ui/dist/js/bundle.js:97429:13)
    at Object.<anonymous> (/home/sylwia/.luna/config/luna-studio/1.4.0.19/atom/packages/luna-studio/node_modules/luna-basegl-ui/dist/js/bundle.js:385:12)
    at Object.install (/home/sylwia/.luna/config/luna-studio/1.4.0.19/atom/packages/luna-studio/node_modules/luna-basegl-ui/dist/js/bundle.js:73807:64)
    at /home/sylwia/.luna/config/luna-studio/1.4.0.19/atom/packages/luna-studio/lib/luna-node-editor-tab.coffee:21:46
    at LunaNodeEditorTab.module.exports.LunaNodeEditorTab.attached (/home/sylwia/.luna/config/luna-studio/1.4.0.19/atom/packages/luna-studio/lib/luna-node-editor-tab.coffee:201:25)
    at space-pen-div.View.element.attached (/home/sylwia/.luna/config/luna-studio/1.4.0.19/atom/packages/git-plus/node_modules/space-pen/lib/space-pen.js:164:63)
    at space-pen-div.CustomElementPrototype.attachedCallback (/home/sylwia/.luna/config/luna-studio/1.4.0.19/atom/packages/git-plus/node_modules/space-pen/lib/space-pen.js:51:55)
    at atom-pane.PaneElement.activeItemChanged (/tmp/.mount_luna-sVaV28g/usr/third-party/atom/usr/share/atom/resources/app/src/pane-element.js:144:24)
    at Function.module.exports.Emitter.simpleDispatch (/tmp/.mount_luna-sVaV28g/usr/third-party/atom/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/tmp/.mount_luna-sVaV28g/usr/third-party/atom/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.setActiveItem (/tmp/.mount_luna-sVaV28g/usr/third-party/atom/usr/share/atom/resources/app/src/pane.js:316:28)
    at Pane.module.exports.Pane.addItem (/tmp/.mount_luna-sVaV28g/usr/third-party/atom/usr/share/atom/resources/app/src/pane.js:539:20)
    at Pane.module.exports.Pane.activateItem (/tmp/.mount_luna-sVaV28g/usr/third-party/atom/usr/share/atom/resources/app/src/pane.js:468:20)
    at Workspace.<anonymous> (/tmp/.mount_luna-sVaV28g/usr/third-party/atom/usr/share/atom/resources/app/src/workspace.js:1161:20)
    at next (<anonymous>)
    at step (/tmp/.mount_luna-sVaV28g/usr/third-par
```
